'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Header from '../../../components/Header';

export default function MaintenancePage() {
  const [items,setItems]=useState<any[]>([]); const [stats,setStats]=useState<any>({}); const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch('/api/landlord/maintenance?role=landlord').then(async r=>r.ok?r.json():{requests:[],stats:{}}).then(d=>{setItems(d.requests||[]);setStats(d.stats||{})}).finally(()=>setLoading(false))},[]);
  const statusClass=(s:string)=>s==='COMPLETED'?'bg-emerald-100 text-emerald-700':s==='IN_PROGRESS'?'bg-blue-100 text-blue-700':'bg-amber-100 text-amber-700';
  return <div className="min-h-screen bg-slate-50"><Header/><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/landlord" className="text-sm font-bold text-blue-600">← Landlord dashboard</Link><h1 className="mt-2 text-3xl font-black">Maintenance</h1><p className="mt-1 text-slate-600">Track repair requests across your properties.</p></div><Link href="/services" className="rounded-xl bg-slate-950 px-4 py-3 text-center text-sm font-bold text-white">Find a service provider</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Open',stats.open],['In progress',stats.inProgress],['Scheduled',stats.scheduled],['Completed',stats.completed],['Emergency',stats.emergency]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><div className="text-sm text-slate-500">{a}</div><div className="mt-1 text-2xl font-black">{loading?'—':b||0}</div></div>)}</div><div className="mt-8 overflow-hidden rounded-3xl bg-white ring-1 ring-slate-200"><div className="border-b border-slate-100 px-6 py-4 font-black">Requests</div>{loading?<p className="p-6 text-slate-500">Loading…</p>:items.length===0?<p className="p-8 text-center text-slate-500">No maintenance requests yet.</p>:<div className="divide-y divide-slate-100">{items.map(x=><div key={x.id} className="p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><strong>{x.title}</strong><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusClass(x.status)}`}>{x.status}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{x.priority}</span></div><div className="mt-1 text-sm text-slate-500">{x.property?.title} · {x.category}</div><p className="mt-3 text-sm text-slate-700">{x.description}</p></div>{x.cost?<div className="font-black">K{Number(x.cost).toLocaleString()}</div>:null}</div></div>)}</div>}</div></main></div>
}
